interface ILogger {
    Trace(message:string) : void
    Debug(message:string) : void
    Info(message:string) : void
    Warn(message:string) : void
    Error(message:string) : void
    Fatal(message:string) : void
    Trace(message:string, e:Exception) : void
    Debug(message:string, e:Exception) : void
    Info(message:string, e:Exception) : void
    Warn(message:string, e:Exception) : void
    Error(message:string, e:Exception) : void
    Fatal(message:string, e:Exception) : void
}
