class MainWindowViewModel {
    - {static} <<readonly>> maxResultCount : int = 1000
    - {static} <<readonly>> imageCountPerPage : int = 50
    - disposables : CompositeDisposable
    + logger : LogMessageNotifier
    + progress : ProgressNotifier
    - webImageStore : WebImageStore
    + SearchCommand : ReactiveCommand <<get>>
    + CancelCommand : ReactiveCommand <<get>>
    + SearchWord : ReactiveProperty<string> <<get>>
    + Images : ReadOnlyReactiveCollection<WebImageViewModel> <<get>>
    + SelectedImage : ReactiveProperty<WebImageViewModel> <<get>>
    + PercentProgress : ReactiveProperty<double> <<get>>
    + StatusMessage : ReadOnlyReactiveProperty<LogMessage> <<get>>
    + ErrorLogs : ReadOnlyReactiveCollection<LogMessage> <<get>>
    + ErrorLogsVisibility : ReactiveProperty<Visibility> <<get>>
    + ClearErrorLogsCommand : ReactiveCommand <<get>>
    + PageNumber : ReactiveProperty<int> <<get>>
    + PrevPageCommand : ReactiveCommand <<get>>
    + NextPageCommand : ReactiveCommand <<get>>
    + HeadPageCommand : ReactiveCommand <<get>>
    + TailPageCommand : ReactiveCommand <<get>>
    + MainWindowViewModel()
    - InitializeSearchBar() : void
    - InitializeThumnailBar() : void
    - InitializeStatusBar() : void
    - SearchImage() : void
    + Dispose() : void
}
